name: "Semantic release"

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next

concurrency:
  #  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  setup:
    name: Set environment variables
    runs-on: ubuntu-latest
    outputs:
      DEPLOY_ENVIRONMENT: ${{ steps.env.outputs.DEPLOY_ENVIRONMENT }}
    steps:
      - name: "☁️ compute environment variables"
        id: env
        run: |
          echo "DEPLOY_ENVIRONMENT=$([[ ${{ github.ref_name }} == 'main' ]] && echo 'production' || echo ${{ github.ref_name }})" >> $GITHUB_OUTPUT

  release:
    environment:
      name: ${{ needs.setup.outputs.DEPLOY_ENVIRONMENT }}
      url: https://github.com/${{ github.repository }}/releases/tag/${{ steps.semantic-release.outputs.release-tag }}
    outputs:
      release-tag: ${{ steps.semantic-release.outputs.release-tag }}
    name: Semantic release
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "🚀 release"
        id: semantic-release
        uses: tmcb-space/release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs:
      - release
    if: ${{ needs.release.outputs.release-tag != '' && github.ref_name == 'main' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
